# Generated by Django 3.2.14 on 2022-07-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_producto',
            options={'ordering': ['id_tipo_producto'], 'verbose_name': 'Tipo de Producto', 'verbose_name_plural': 'Tipos de Producto'},
        ),
    ]
